# Generated by Django 4.1.5 on 2023-02-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_requested", models.DateField(blank=True)),
                ("employee_name", models.CharField(max_length=100)),
                ("is_sick", models.BooleanField(default=False)),
                ("is_personal", models.BooleanField(default=False)),
                ("is_paid", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_by", models.TextField(max_length=100)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
