# Generated by Django 4.1.5 on 2023-02-04 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="date_requested",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
