# Generated by Django 4.1.5 on 2023-02-04 18:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_leaverequest_date_requested"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="date_requested",
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
