# Generated by Django 4.1.5 on 2023-01-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField()),
                ('capaciy', models.IntegerField()),
                ('fare', models.FloatField()),
                ('passengers', models.IntegerField()),
                ('notes', models.TextField(default='', null=True)),
                ('taxi_number', models.IntegerField(default=111)),
            ],
        ),
    ]
