# Generated by Django 4.1.5 on 2023-01-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taxi',
            old_name='capaciy',
            new_name='capacity',
        ),
    ]
